apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebas-pantry-api-dev
  namespace: dev
  labels:
    app: rebas-pantry-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rebas-pantry-api-dev
  template:
    metadata:
      name: rebas-pantry-api-dev
      labels:
        app: rebas-pantry-api-dev
    spec:
      containers:
        - name: rebas-pantry-api-dev
          image: ghcr.io/zgamelogic/rebas-pantry-api:development
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Chicago"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
