apiVersion: v1
kind: Service
metadata:
  name: rebas-pantry-api-dev
  namespace: dev
spec:
  selector:
    app: rebas-pantry-api-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
